"""phase2 kb_chunks with pgvector

Revision ID: bdc12d4c41f9
Revises: 27aa976f597e
Create Date: 2026-08-23 03:36:05.842387
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision = 'bdc12d4c41f9'
down_revision = '27aa976f597e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('document_name', sa.String(length=128), nullable=False),
    sa.Column('section', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('embedding', Vector(dim=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_chunks_chunk_id'), 'kb_chunks', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_kb_chunks_document_id'), 'kb_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_chunks_document_id'), table_name='kb_chunks')
    op.drop_index(op.f('ix_kb_chunks_chunk_id'), table_name='kb_chunks')
    op.drop_table('kb_chunks')
    # ### end Alembic commands ###
